### ISSUE TITLE
Game menu

### ISSUE THREAD

**Issue by Leticiel** [AtomCrafty/UniversalInjectorFramework#10]
May I ask if UIF can modify this kinda menu?

![Screenshot 2024-06-04 161805](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/155957757/34940ff7-d995-4cbf-8be3-735471112d74)

Here is the exe file:
[sisters.zip](https://github.com/user-attachments/files/15545926/sisters.zip)

Config file:
[uif_config.json](https://github.com/user-attachments/files/15545997/uif_config.json)

**Comment by AtomCrafty** [comment]
UIF can only intercept programmatically created menus. This one is loaded from an embedded resource.
You can use [Resource Hacker](https://www.angusj.com/resourcehacker/) to modify the menu resource.
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/4553050/f8c2a071-23f1-4a2b-ada3-eb3f686e9fc2)
