### ISSUE TITLE
Unable to replace charater

### ISSUE THREAD

**Issue by jyxjyx1234** [AtomCrafty/UniversalInjectorFramework#6]
when I use character_substitution or text_processor, the log both show that it hook sucessfully.
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/86876769/13b7c7b5-945e-4bb7-ae80-e21cd2aab208)
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/86876769/7b3a8d8e-c8bd-438e-b9d7-b77320a4ee59)
However, the charater didn't be replaced. (It should be "这" instead of "這")
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/86876769/1160c8db-eead-4fa3-99c8-7792c8504cbb)
Here is the exe file, it uses Exhibit Engine.
[ExHIBIT.zip](https://github.com/AtomCrafty/UniversalInjectorFramework/files/14981652/ExHIBIT.zip)

**Comment by AtomCrafty** [comment]
Please post the full config file.

**Comment by jyxjyx1234** [comment]
Here is the config file.
[uif_config.json](https://github.com/AtomCrafty/UniversalInjectorFramework/files/15024218/uif_config.json)
Additionally,I tried to change my font to repalce the charactor,but the font manager also can't take effect.

**Comment by AtomCrafty** [comment]
[uif_config.json](https://github.com/AtomCrafty/UniversalInjectorFramework/files/15024377/uif_config.json)
Please try this config and post the console output.

**Comment by jyxjyx1234** [comment]
Here is the output.The  charater also didn't be replaced this time.
`[injector] ======================================================
[injector] Injecting into module ExHIBIT.exe at address 00400000
[injector] Loading original library from C:\Windows\system32\winmm.dll
[text_processor] Hooking import MultiByteToWideChar in ExHIBIT.exe at 0045C180 --> 5438EB70
[text_processor] Hooking import GetGlyphOutlineA in ExHIBIT.exe at 0045C02C --> 5438F030
[text_processor] Unable to hook import GetGlyphOutlineW because it does not exist
[text_processor] Hooking import GetTextExtentExPointA in ExHIBIT.exe at 0045C020 --> 5438F2E0
[text_processor] Unable to hook import GetTextExtentExPointW because it does not exist
[text_processor] Hooking import GetTextExtentPoint32A in ExHIBIT.exe at 0045C030 --> 5438F5B0
[text_processor] Unable to hook import GetTextExtentPoint32W because it does not exist
[text_processor] Unable to hook import GetTextExtentPointA because it does not exist
[text_processor] Unable to hook import GetTextExtentPointW because it does not exist
[text_processor] Hooking import TextOutA in ExHIBIT.exe at 0045C024 --> 5438FA70
[text_processor] Unable to hook import TextOutW because it does not exist
[text_processor] Hooking import AppendMenuA in ExHIBIT.exe at 0045C500 --> 5438FCD0
[text_processor] Unable to hook import AppendMenuW because it does not exist
[text_processor] Unable to hook import InsertMenuA because it does not exist
[text_processor] Unable to hook import InsertMenuW because it does not exist
[text_processor] Hooking import InsertMenuItemA in ExHIBIT.exe at 0045C418 --> 54390090
[text_processor] Unable to hook import InsertMenuItemW because it does not exist
[text_processor] Unable to hook import ModifyMenuA because it does not exist
[text_processor] Unable to hook import ModifyMenuW because it does not exist
[text_processor] Unable to hook import SetMenuItemInfoA because it does not exist
[text_processor] Unable to hook import SetMenuItemInfoW because it does not exist
[text_processor] Hooking import SetDlgItemTextA in ExHIBIT.exe at 0045C4CC --> 54390630
[text_processor] Unable to hook import SetDlgItemTextW because it does not exist
[text_processor] Hooking import DrawTextA in ExHIBIT.exe at 0045C49C --> 54390770
[text_processor] Unable to hook import DrawTextW because it does not exist
[text_processor] Unable to hook import DrawTextExA because it does not exist
[text_processor] Unable to hook import DrawTextExW because it does not exist
[text_processor] Unable to hook import GrayStringA because it does not exist
[text_processor] Unable to hook import GrayStringW because it does not exist
[text_processor] Unable to hook import TabbedTextOutA because it does not exist
[text_processor] Unable to hook import TabbedTextOutW because it does not exist
[text_processor] Hooking import MessageBoxA in ExHIBIT.exe at 0045C4D4 --> 54391810
[text_processor] Unable to hook import MessageBoxW because it does not exist
[text_processor] Unable to hook import MessageBoxExA because it does not exist
[text_processor] Unable to hook import MessageBoxExW because it does not exist
[text_processor] Unable to hook import MessageBoxIndirectA because it does not exist
[text_processor] Unable to hook import MessageBoxIndirectW because it does not exist
[text_processor] Hooking import DefWindowProcA in ExHIBIT.exe at 0045C518 --> 54391D70
[text_processor] Unable to hook import DefWindowProcW because it does not exist
[text_processor] Unable to hook import DefDlgProcA because it does not exist
[text_processor] Unable to hook import DefDlgProcW because it does not exist
[text_processor] Unable to hook import DefWindowProcW because it does not exist
[text_processor] Unable to hook import DefDlgProcA because it does not exist
[text_processor] Unable to hook import DefDlgProcW because it does not exist
[font_manager] Imported 2 font(s) from WenQuanYi_CNJP.ttf
[font_manager] Unable to hook import CreateFontA because it does not exist
[font_manager] Unable to hook import CreateFontW because it does not exist
[font_manager] Hooking import CreateFontIndirectA in ExHIBIT.exe at 0045C098 --> 54386A80
[font_manager] Unable to hook import CreateFontIndirectW because it does not exist
[font_manager] Unable to hook import CreateFontIndirectExA because it does not exist
[font_manager] Unable to hook import CreateFontIndirectExW because it does not exist
[locale_emulator] Codepage 936 matches expectation
[injector] Initialization complete
[injector] ======================================================
[text_processor] NCCREATE: 1/1 rules applied, 1 successful
[text_processor] 鋼炎のソレイユ－ＣｈａｏｓＲｅｇｉｏｎ－
[text_processor] 钢炎のソレイユ－ＣｈａｏｓＲｅｇｉｏｎ－
[text_processor] NCCREATE: 1/1 rules applied, none successful
[text_processor] AppendMenuA: 1/1 rules applied, none successful
[text_processor] NCCREATE: 1/1 rules applied, none successful
[text_processor] MessageBoxA: 1/1 rules applied, 1 successful`

**Comment by AtomCrafty** [comment]
Looking at other ExHIBIT games I have installed, they seem to all include a file called `resident.dll`, which also imports text drawing functions. Let's see if it works if we inject into that as well.

[uif_config.json](https://github.com/AtomCrafty/UniversalInjectorFramework/files/15025414/uif_config.json)

**Comment by jyxjyx1234** [comment]
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/86876769/330edcef-d2ee-4a48-9c53-5487547b7c84)
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/86876769/d87806b3-f263-44cf-8c35-9ea29b4f337a)
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/86876769/a788b4ff-016a-4462-819e-85a9538f7d85)
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/86876769/e1ca25e4-f63a-44e5-a687-df0914bf4eda)
It seems that someting strange happened.

**Comment by AtomCrafty** [comment]
That appears to be an issue with my implementation of the `GetTextExtentExPointA` hook. It's a non-trivial fix, so I don't know when I'll get around to it.

**Comment by jyxjyx1234** [comment]
Something interesting happened. When I set the text_processer as false,and use a Chinese font in font manager , the program become to use the GBK encoding rather than sjis (I don't know why), so I just need to use GBK encoding in the rld script. and don't need to use the  text_processer now. Thank you very much.

**Comment by Cosetto** [comment]
![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/81801486/ee3bb834-a773-4ecc-9418-a0197c26fc02)
Well actually, the font settings of Exhibit are in "resident.dll" not the .exe

**Comment by AtomCrafty** [comment]
> Well actually, the font settings of Exhibit are in "resident.dll" not the .exe

That's why the last config I posted injects into resident.dll

> the program become to use the GBK encoding rather than sjis

No idea what's going on there, but I'll assume that solves your problem.
