### ISSUE TITLE
[character_substitution] Unable to hook-realLive engine

### ISSUE THREAD

**Issue by pxBang** [AtomCrafty/UniversalInjectorFramework#7]
**Description**
Please describe what you are trying to achieve and what you already tried.

When I was using character_substitution, I found that the replacement could not be done properly, and the log showed ‘Unable to hook import TextOutA because it does not exist’. The game uses the realLive engine. How can I solve the problem？

Looking forward to your reply！

**UIF config**
Please upload your `uif_config.json`

[uif_config.json](https://github.com/AtomCrafty/UniversalInjectorFramework/files/15036783/uif_config.json)

I have added the exe file for you to check, the link to the exe file is as follows
[exe.zip](https://github.com/AtomCrafty/UniversalInjectorFramework/files/15036850/exe.zip)

<details>
<summary><b>Console output</b></summary>
<pre>
Paste your console output here.

Universal Injector Framework, created by AtomCrafty, 2021
Loaded configuration:
{
    "allocate_console": true,
    "character_substitution": {
        "enable": true,
        "source_characters": "這説為凜們時過対麼瑤還現髪種樣見経頭書実開両動話問間論長進義給関別門覚復難東応風張認伝題処馬詩讓愛師語変爾許結邊歴記読識戰徳術遠総観遙槇連強則該堯場軽親統龜帯業産臉雖軍極類満転歩剣黒離電毎飛済藝衆殺報車終紅視誰絶確達驚羅楽資運華傷評響剛談領権晩興齧顕圖銭楊態霊訳鄰歓錯聯計紀請創陽選緊単詞調編異員僅勢講齡漢証較撃厳竜約蘭質鉤幇陸鉄節細筆値陳熱蘇齣懐媽際級悪須維挙専導備務簡費脳雑亜顧歳構隊魯続劇聞爺敵規陣習線樹階訴設謂囲議謝録層標揺帰劉斉戯隠鉋尋査試飯漸護組勝喬釈討験買貴継団適農嘆衛麗塊宮環齒換倫敗圧聖責絲骭頁険頓孫鳳薬婦韋養裃園紙労鐘揚誤齊劃揮畢負寧鼡銀諸陰呉趙閃納罷遺順輯郷臨堅頂練緩増職鼕館偉獲勁槍滅皷罵輩憶優預擇補貝鮮織積暁売倣載鼈盧諾偸夥純課鼇営黨啓紛擺弾財賞盤牆點豐頗賛圓紹縦賈執慮煩黐嚇鬧魚縁閑黌騎鏡庁誠焼傾韓戸叢緑慣搶項蕭鎮島栄鎬躍顔審軟擁貼礎謀飄訓閉塵窮湯憂蕩麭藍淨辯訪蒼憤撲薩県豈奮奪慶澤輪針監寛鋒緒遅側粛鶏潔儀穏烏躱鄭徹銷滾鳥廃瘋聡測渉姉襲獄毀飲閲検麪麩縮嘗濃麥麕麌賽貨掲協賊厭輸騙喪麁奨橋瑪勧邏鳴鹽減掃損悶詳爛庫朶鹹繞馮呂絵頼鷽碼顫競貧帥閣鷭貫渾鷏暫艦鷆夾飾倆獸壇賢賓鎖蓮牽諍轟匯騰額鑑輝纏喚訊霧遷悩並舗訂闊臘齢帳皺錚紐賦駕購塗鶺顆拡艶痩喩禍艱鶸鷁鷄凱遜鋼臓廟逓鋭鶲撫鴻鶤鵺趨暈嬌擠鑚鈕鍵倶銅縄懸絡貢鵬鵯鶫諷茲違呑煉鶇駆災譜頌擾偽篭輌猟餓膚績虧噴楓汚賭鵙鵐誕暢闡贏攬潤鵤錦懶斬簽鵞歯罰撥鵈擬誘瓊馳臥憲郵桜縫饒賀訝綜欄溝謹厖療邁窪摂渇鈴飽湊糾櫃燭顛嬰嘯犠袙覧貪綿鵆闖鴾鷹謙焔隣窩脇諒幣腸頑騒紋綱鵁斎嗚鴒刪溌擲頻驃滬鵄鶯亀贈侖頚鴪聳襯墜綉鴃駛鳫詢釘蘊賜諧鴈鳰鍋鶴詭詐駐賎駁寵厠唖瑩億畳駭漁頬攤鳧縛簾欽軌籌竄鈞鱶潰鱧遼貶軒鱚瞞鴉僂鰾鈎錫鱆嚢飢誼謬賺鱇窺鰰塩鰡竪獅脹貞輔滄誦繊銘償驕譚瀟墳嘩紗粧荊羨擱兪鰤詫鏈壷貿濫賠鰛釵倉債鰮滲渋凍燦淪採鰄謡謎聶鰊瑣穎鰒鰈膩鑰姪甎漲鰆懲闘餅絋諱訣斃灘販鰌鰉崗鰔揀廂尭鋳譏傘驟鰕轎昿鯰嶺鯱縷殻禿儲娯鯲腫鰺侶蝋棟綻鯔朧鯣偵鯒妬鮑瀾鉱鯑懇鯏煥繆鯆濺鮹鮴黴駱鮨鮠鮗爍膠摯鮖慚綺嵐栲鴛驢駝鮓頽箋剤輿鬪吶隴廬閨閻診擣籃艙頃銜鴨鬨覓駿傭漿貸鬥鬚鬘綢鵝鬆岡髷鈔鞏鴦嘔髱髴悵撹髮髣髢驀鵲巣鴬碩鑿髞蝕體驫驗竇驛釀驅鳩盞騷駲紳錘駮囂馼塁陜饑虜勲蘿軸壟鍛狽誣矯歛繃濱綽讚誅饐禎饂蟻糞洶蔭誇詔絨龍詛餽蕪頤辮餬閥餠餤濁餝餘薫餔篤穢硯釣飃掻撈襪颱颪緞顳顯顋醤幀幟竅顏僑譴簫鵑鈑蝿憫鉛贖憊綴繹頸韲絞韈詮韆鞴鞐羈錐梱鞦誡頒諦翹鞨澆獰熾漣聾絆瀉袞訶鞜鞆懴靺鞁靹瀘靱憚暉驤撓諭靤櫓鰐靜閔轍瓏諌靉蝦靈蹌靆霤逕霙兌輓雜訟襍隸靭鬢隱闕賄嶄軾險陦陝鱗陞鈍滸嘖陏阯韃鰲阨闢關闍馴濶閧頷躊閠婁鈬鉉閙鴿閖閊渦懾閇钁駅薐籬蛍輾墾鑽謨顱鑵釟儼檸桟絹謗竃鈩詣倹鑪柵饅轄棗鑢嫋鑛鑄贅鑒鑁鐡輳闌鐵癆緬鐶鹸輒馭韜喞鐇鐓畝鐔鐚繚絳僥誨檻褻饋塢鏝紂噸鏥鎹涜諜鋸鎔鄒訛鐸薔瀏鐙攅紡鎭鍖雋惻紜鍮鍼鍠鍜緯錻楡瘡讒鑼緝躡錵錺釁綏矚錣駒錢鍄蠱鋺錏鋩銛獎締癲瀝鉐儂鴎鋤銕鉈鉅參襖詰釿貽靂燼釶葦嗇繭頡簒釼錮蛻釛釡釖餌鉗釐闔詁綾鯨釋醯醫醂謁嫻酳酘軼騁酖愴髏澗邉遲腎隨氈巓璽鉢轅絢飆遶賍漬遯遞諺誹騾蟄縹遖遉逎逹癩藹逧藾窯迴邇鐺磽殱瀕迯迚辷駢辭轣雛轢佇謔緲滌轜銹轗轉轌鯊諳輹諄磯靄颯謫渙輛輙軣軈嶼賂軅躾曖軆鸞軋緋躰貳鏗躙躔綸躄鸚閘蹠濾蹤搾蹐踴魘踰慟唄踐梟貯跿踈纓跼赱贔贓贐贊匱膾賻輟篩錠賣歟賤貮撻訥貭飼戝膿釧豼貎貍霑詼纜霽餃殯塋閂鶚錨繽鏘豬隕豎谺讙閹痺讌讀譽譯緘譟鹵餉葷譖輻證燉譌謚譁謠鵡諡鎧謌鐐諠紺諫諚誂巒觸謐靫觧觝觀蹣覽蝟簍覺覩覊覈襾襷躪襴鷲慫襭懣囁觴哢褝牘襌褞鯉褌褄裲裝裄礫攣謳袿軻袰袮袗鎌諂詆袵衵衞欒衒餒驥衂驍衄蠻餡蠧齪餞蠶蠑蠎齷蟷蠍蠏潁蟲蟇蟐螢蠅囈蝪蝨嶇蜑閭蛯蛬蠣靦蚰號乕虍蘰蘆鷺蘋蘓藥諛薹顰痙蕷藪鏤薑薀臍蝸蕋蘂蕣褸蕀蔔謾龕慂溏蔕蔟騫鴣蔘襤蓆嫗蓚噛蒻欖濘蓙蒟煬皚葢輦葹驪鷓葯飩萬轆葮蒭蒄曁蕚綰銓鉞儷曇駄贍萪菻儻駟躋蔆萠萢菷崢菎枠菫萓菴贄荵荳鵠讖莵嚀嬪莊莇鐫茣莖莟莚閏脛誥茘譎荅茖苙茆嚶苺襠苳艸鯤艷漑舮薈殤擯艪艨瞼覦艢芻艟艚犢艝綬鄲艀舩舖鴇歿舊與鸛檳臺臟覬飭塹臈臙臑膽膸膵慍櫚膰膓賁羶鳶腟膣膤膕膃諢腦脣脩肬冐肭肅聽聹聰捫聲聨聢鍍顎聟耡鷦靨飜翆譱羮覲羣羇羃銖羂罸輕罧罌薊罠罎鮟纎轡纖纔纐纒鶻續繿緕纃鑞繻繼繩鈿繪繙繖繧鯀縺繦縱縒縡縣縅誚緻緤颶綟緜殞綯總綫綵綛絽襃徠經絣饗絏絎縉絖紵紮絅詬糺鳬橢糴縊糒糘鶩糂鍬糀粨粡粫粢粭粐浹粃籵曄訐籖籤籟籘軫奩籐籏籔簷篶鴕簗簓簀蘚殫籠儕愾簔簑縟篏箙幃箏箒箚箟鑾箘筬獪筰筴筥筅饌筍筺騅笶笵笘笂甌竢竡竝竚竓竏謄訖誑竍竊窰儔竈穽龝穩椏穉穃稾稱稟稙稘鑠顴秡潯槞秬禮禪齋繝贋繕禝瘧縵祿祕礙篋礑賃讎礒礇磚奐儺磑藺簣嬋碯碪賑緇碵碆硴礪砠礦矼矇飴瞹瞶眛眥眞眤盻餾蘯盪莢盡皹皰皃囀鴆絛皀鰍發訌癶媼癧癪癨癢癡鱸癜癈穡瘻瘉犖痳痲痃疳疂櫛螻疉疊疇鑷當畭畫畧縞畩槧畆畉畊畍畄檣紕齟尢甼瀬甦甞甕甅轂甃瓸齬訃瓱瓰瓲瓩瓧瓔幗珸瑯璢僉珎獻獵獨魎梔猯狹狢狆犲蓴鶉犧獺犇犂鴟牴牋綣牀爼爲爭爐燿燵薺燬燒隲燗熕燻紆稈黷櫺煖熈煕鍔烋烱詒灣鷙饉竰鰻灑煢騏瀰瀁瀋濛諤濔駻濕濟躑齎謖澪濆廩澣摶堊澑濳鏃潛澀澁滷滯滉溂磧滿渟湶渮淕淺駑淒渕濤鰥諞浤洳洟覯泙沺泝沒汳篳沚沍汢氣毬毟毆殼殲殪廡殕殘殀歸歡歐齦飮盜錙欟鬱欅蘢鬮櫻櫟櫑櫞蘗閼飫檢檍鷂樢樸橸樶橲慳樌樓櫁樒覡槫樔蕎槭誄樞槹權樛樂槨榠榑樮槝榾槓榿榮榲楪蕘檪榁楙楴椹銃楾楜輊棆椡椣椚蕁椪闃椨縋棯椥椄齲椶棧棔椌癬棡椦椢椈橈棊桾憮梍梺鮫梠梹檮梛條桿瘍桙栫桍驂痾懍栞檜柧柆柎枹貲柮柤枴枅銑枡輜臚礬枦枌枩杤杣杙朷朸杁朿朮朞朖滝鮎朏曵曠曚暸暼曉暘暎暃晢晧晝晉晄昜旡旙旛斷變斂喰數鬩敘敍攷攴攜擽擴軛擶擡舉擧據攪摎臠瀲傴搨搗攝鯢鰭搆搖掵癇魴掟閾掫掎櫪挾鐃拵挧挌萇癰珱擔拑抃抂扨扠扞苧戲戞戉戀懼懽懺憺懆懃懷應憑憇憖憙慓慱慥慯慴慙慘慄愽戔愼惱闥愡愃惷悽忰惓躓惡悋悧悗悁恆恊恟恷鷸怺怱緡怐恠悳從徑彿輅徃彡彙彑彎彌彈彁羆弸弖彜弉廸廴廰廳廱廢廚廝廣廏廐廈廁幵鰓幤幎黽帶帋巵巛巖巉嶐嶽嶮嶬嶝嵶嵳嵎嵒鋏崘鮭崙崚崑崟嵜崕崋嶌峺峽峩萵峇岾頏峅岼岶岻妛癘潟屶蒔乢屮屬屓嘸屆覘賚尨尠尓冪對鎰鮒專將尅轤寳譫鵜齏寶寫寢蹕實寉寃斈學孅竕駘孃嬾鱈嬶嫐糶嫺娵婬娚姙侫妝奬奧竒夲夬艫夛譛夐壽壼壻懌壺壯壜壥壘壗壓墮墸墻壞墺墫墹堽塰塲堝埣埖埓鏨埆垰垪垤垳垉坿垈鉚埀坩圸圷圦鱒團壙圍國圀琺囮囓囑囎愨囃嚴嚮嚥嚔嚠嚊營剴噐嗹咼喨單啝唸啗啅啌啣啀唹哘鰹咾咥鏑咢呰呟吽叺雙厰剄卻夘卩覿凖卍丗卆區紲匸匳勹鷯勸勵纉勳勠勦勣勞勗勍劵劼辧劑剱劒劔劍剳筧剋剏刧刔刋鮃刄凾凵琿凩處凅冱冫冩冦冖冓冑冏囘冂兩竸兒儚鮪儖儁樅儉價僣僞傳僊傚偖偐會伜倅俥俤俛俔儘來侘仭黶仂亰亠亞弍亊亅亂乂丿丼丶鉦丱弌椀亙艤錬憐暦隷涙齠瑠糧稜瞭涼葎裡裏慾葉遊縲猶湧癒鑓匁籾戻杢黙網麺無夢粍脈麿侭桝柾槙釦僕鉾豊砲峯穂諏鋪辺箆塀併雰鈷仏蕕払淵複鋲氷俵柊毘樋釆鯡範汎氾塙噺抜醗発畠畑筈硲萩楳盃拝覇覗廼禰韮駸匂弐貰畷楢薙齶瀞椴栃峠働燈梼嶋兎澱紬嬬辻槻栂塚鎚捗勅銚聴徴彫弔瀦酎註築恥歎蛸皸凧託択瀧辿鯛騨楕詑揃蔵鎗荘窓蟶捜惣遡疎曽岨糎薦栴蹟跡塒隻製棲摺椙髄酔粋醸譲穣壌剰窶乗鍾衝纈昇廠藷準楯従醜週讐蒐繍収呪捨舎偲鏐篠蔀雫宍鴫児諮誌糸屍讃錆鯖皐冊糲笹碕埼榊堺冴砕瑳込狛穀麹閤砿紘広紿効倖檎後個絃捲圏決傑罫繋渓恵係繰粂駈粁脅況兇禦拠喫気機棄蟯幾願翫巌舘陥櫨潅幹姦巻乾苅栢蚫鞄樺椛梶橿樫掛穫浬蓋廻壊蔦菓箇価仮贇沖於薗煙詠榎頴洩叡嶢雲噂欝韻鰯稲壱闇扱蜆鯵穐齔姶鱠",
        "target_characters": "这说为你们时过对么她还现发种样见经头书实开两动话问间论长进义给关别门觉复难东应风张认传题处马诗让爱师语变尔许结边历记读识战德术远总观呢吧连强则该啊场轻亲统吗带业产脸虽军极类满转步剑黑离电每飞济艺众杀报车终红视谁绝确达惊罗乐资运华伤评响刚谈领权晚兴哪显图钱杨态灵译另欢错联计纪请创阳选紧单词调编异员仅势讲办汉证较击严龙约兰质够帮陆铁节细笔值陈热苏沉怀妈际级恶须维举专导备务简费脑杂亚顾岁构队鲁续剧闻爷敌规阵习线树阶诉设谓围议谢录层标摇归刘齐戏隐跑寻查试饭渐护组胜瞧释讨验买贵继团适农叹卫丽块宫环份换伦败压圣责丝赶页险顿孙凤药妇韦养卡园纸劳钟扬误咱划挥毕负宁您银诸阴吴赵闪纳罢遗顺辑乡临坚顶练缓增职啦馆伟获劲枪灭懂骂辈忆优预择补贝鲜织积晓卖仿载桌卢诺偷伙纯课厉营奶启纷摆弹财赏盘墙爸丰颇赞圆绍纵贾执虑烦爹吓闹鱼缘闲妮骑镜厅诚烧倾韩户丛绿惯抢项萧镇岛荣搞跃颜审软拥贴础谋飘训闭尘穷汤忧荡碰蓝净辩访苍愤扑萨县岂奋夺庆泽轮针监宽锋绪迟侧肃鸡洁仪稳乌躲郑彻销滚鸟废疯聪测涉姊袭狱毁饮阅检倘傻缩尝浓丫乔挡赛货揭协贼厌输骗丧躺奖桥玛劝逻鸣拖减扫损闷详烂库朵嘿绕冯吕绘赖哼码颤竞贫帅阁姬贯浑丢暂舰瞪夹饰俩兽坛贤宾锁莲牵睁轰汇腾额鉴辉缠唤讯雾迁恼拼铺订阔腊龄帐皱挣扭赋驾购涂嗯颗扩艳瘦喻祸艰扯裤踢凯逊钢脏庙递锐摔抚鸿砍盯趋晕娇挤钻纽键俱铜绳悬络贡鹏怔喂讽兹违吞炼嘻驱灾谱颂扰伪笼辆猎饿肤绩亏喷枫污赌扔吵诞畅阐赢拦润唉锦懒斩签撑齿罚拨盼拟诱琼驰卧宪邮樱缝饶贺讶综栏沟谨庞疗迈挖摄渴铃饱凑纠柜烛颠婴啸牺帕览贪绵婷闯啡鹰谦焰邻窝胁谅币肠顽骚纹纲咖斋呜脖删泼掷频镖沪歧哎龟赠仑颈晌耸衬坠绣愣驶玫询钉蕴赐谐邓砸锅鹤诡眨驻贱驳宠厕哑莹亿叠骇渔颊摊谎缚帘钦轨筹窜钧嚷溃煞辽贬轩尬瞒鸦搂尴钩锡绑囊饥谊谬赚甩窥糕盐咕竖狮胀贞辅沧诵纤铭偿骄谭潇坟哗纱妆荆羡搁俞哟诧链壶贸滥赔耍钗仓债喔渗涩冻灿沦踩棵谣谜聂趟琐颖磕砰腻钥侄砖涨啥惩陡饼逛讳诀毙滩贩嗓媳岗叁捡厢尧铸讥伞骤塌轿旷俏岭芷缕壳秃储娱咪肿账侣蜡栋绽咦胧胳侦钰妒鲍澜矿郝恳桢焕缪趴溅撇挪霉骆垃啪圾烁胶挚凳惭绮岚烤鸳驴驼眯颓笺剂舆桩呐拢庐闺阎诊捣篮舱顷衔鸭吱觅骏佣浆贷诈碟孽绸鹅詹冈琪钞巩鸯呕烫稣怅搅咚筷嗡蓦鹊巢莺硕凿膛蚀啤垫嘟窦烘酿铮鸠盏拣咧绅锤揪嚣眶垒陕琏虏勋萝轴垄锻狈诬矫敛绷滨绰娅诛瞄祯筠蚁粪汹荫垮诏绒咙诅捂芜颐辫姗阀宓摹浊惕拎薰阱笃秽砚钓蹦搔捞袜龚觑缎噢嗦煜酱帧帜窍噩侨谴箫鹃扳蝇悯铅赎惫缀绎嚎圳绞炜诠妞瘾掐羁锥捆渲诫颁谛翘嘎浇狞炽涟聋绊泻衮诃橱瘫忏睬舔沅泸疤惮晖镶挠谕澈噜鳄噗闵辙珑谏呸虾婧跄娓揽迳璐兑惋唬讼嘀雯韧鬓匀阙贿崭轼盔蚂抨鳞嬷钝浒啧闽屉鞑鳌铲呛恺拽驯肮憋颔踌邢娄踱炫喽鸽飕汴涡慑讪氧驿棱篱萤辗啃婶谟颅缴扒俨拧栈绢谤灶哆诣俭踹栅馒辖枣叽袅钊瞅赘漩婊盎揍阑纨唠缅佬皂辄驭韬唧糙炕亩呃唷缭绛侥诲槛亵馈坞碳纣吨抿铐渎谍锯坷邹讹铎蔷浏蹬攒纺榷吆隽恻纭嬴萦嗳钮纬狰榆疮搀锣缉蹑掳簌衅绥瞩桨驹瞟喳蛊蹭啷湄哧嘈缔癫沥刁哝鸥锄崽骷忡掺袄诘嗒贻雳烬酝苇啬茧颉篡褚锢蜕砆碔偎饵钳疙阖诂绫鲸蕙璜瘩摒谒娴嵇缰轶骋烨怆髅涧烩偌肾跺毡巅玺钵辕绚飙愫赃渍瑷憨谚诽骡蛰缥荃擎楣捅癞蔼乓籁窑晗悻铛跷歼濒琦睽滢骈忒镑雏啰伫谑缈涤匾锈炅乒蹋鲨谙戾谆矶霭飒谪痪跤拴嗨礴屿赂涔啐暧纾鸾轧绯坝贰铿嚅翟纶抡鹦闸搐滤彤榨胭镯魇陇恸呗墩枭贮瘪惦缨攥靶姒潆妩夔匮脍汩辍筛锭睐欤翎咝挞讷嗖饲邺脓钏漪喵洼玷诙缆霁饺殡荧闩鹗锚缤锵弈陨驸晾撂阉痹嚓泾蓓璇缄缜卤饷荤懵辐惬炖忑谥谗罡鹉涣铠馋镣忐绀掂膑掰峦叼谧茬撬滇菀蹒靳猬篓虬囔剁垅撅垦躏鼢鹫怂汶懑嗫觞咔阕牍诩琨鲤樨撵甭媲菇砾挛讴酗轲拄蘸熠镰谄诋荪咻鹂栾荔馁骥峒骁桅毗馅瘸龊饯窠抠剐龌柠斓犷颍稹囱琛靓蛐呓刨哒岖捋闾嗬勰骧腼刽榭啕羿喏坍鹭捎婺焘谀镐颦痉崆梆镂掇戕脐蜗咿瞌翱褛熵臊谩龛恿搪璀诌骞鸪嘭褴胰妪盹啮娣榄泞坳侬炀皑娲辇鳖骊鹧姝饨腌辘婕玑撷暨阂绾铨钺俪昙驮赡嵘孪傥驷跻淄淖佟虢峥砭桦璨擞昕贽舀蹿鹄谶倌咛嫔螃磷镌獠挎氲龇闰胫诰摞谲唰噼噔粼嘤呦裆蛀怵馄庾溉涮荟殇摈俅噶睑觎镳刍嬗磺犊锲绶郸蜓莘漳鸨殁咭铉鹳槟搽坨觊饬堑灏闳颢琮嗑蟑愠榈咂糗贲膻鸢掸绉泠偻碉诨盅睢臃蹩嶙蘑嗥仨赣绌扪忪峋祜镀颚倜镬鹪靥圯叵揿茁觐仃挲剜铢鑫篙氢泵罂蓟卟芮氨骅辔赊苯迤徜鹘邕坯潢菡邋歆娆芊踮碱鬃籽牯鲧遢聩颏跎垛埂耷诮镛咣飓铀殓殒徉侩饪昀锴箩煲徕焱岜飨摁嗲缙邈铝钙纫诟鼹凫椭骛缢傣噙鹜淼锹呤滟踽聃钿炷杈浃搡赅晔讦旎恹玮焯轸奁玟跆恽噱钎鸵橐蘅灞藓殚诿侪忾旖趄缛矸绡帏碴祛谌鼐銮瘀嘁狯裱呲嗝囫馔罄嘹骓囵牖沏阗瓯蚱遛樾痨蒯堇誊讫诳馊郦螅俦鲲膘韪悱桠乩衩姘怄钠醮溧铄颧畹浔栊姣觥氯噘锏赝缮秸疟缦馍哔钤箧鄱赁雠飏趔铖奂傩迨蔺篑婵氖獐赈缁烜绺侗镗邝飚擤涿饴骠闱骢橹酮谯颀馏诤烊荚煨囡哐琰啭鸩绦掼鳅颌讧遴媪铤蔻镭簦纥鲈澍摭穑诓屣荦钹玎茈囤怼栉蝼劢邛昱镊瓴汜蹰芾缟谖椠镫珏犟殛妫樯纰龃鱿锌濑骜峤丏鄢毂夯碜龉讣哙崧咩蕤苕蕻蝈唁臬篾佥撸逦锉蜇魉栀蔫喑诶酶胺莼鹑趼獭庋赓鸱繇儆绻饽艄讵铡趿蒺颛荠嘏娈骘岘鬈锩纡秆黩棂埙顼帼锷祂啵诒缱鸷馑喱鳗暍茕骐郴狲髡涝谔猢焊伧淝踯赍谡轫靛廪猱抟垩渌唿镞瓒嘣钾砝铩酰挹碛掮洚蜢吖煊洱驽喁邬捭鳏谝耦镔餍觏妤鲫璩毽嗵筚铰姹秾潞竽撺枰莒氮阊庑阆珩犄獾猡摀龈勖崴锱莆孬辋茏阄伥焖乜訇佘阏饫滦砉鹞蜮訾嫫锃谠悭钡绔汛雒觋氐瑭荞龢诔榫綦夤鲠兖滁荑泮朓邳挝佤橛撄彀仵荛栎圮崤郜逯铳犍剡轾郇杌蕲涪荨狻阒牦缒荥扃洄黢辏畀嚭沤癣洹屌琊蠲桡瓤唢怃沆泫鲛骝蚍亍嚯旮砣疡帔猕呖骖疴懔崐郓刿舢缃桉赀屺癯龋搠铣冼辎胪矾堞茔橥氅沔镁澶觯阃娌嫘喈鼍泷鲇粑偓殽蘼厝俇鼙侔戆墉虺椤旯岿酽擀鹌硌聱垆鳝妯飧馐阋韫焐暌蚝笤锟髹轭藿赜芰畲傧嫽猓脔潋伛羼珰郅鲵鳍坼坻琬痫鲂洇阈烷锰枥惝铙痱鄯愦苌痈璎顸鳎珉碘趸洮翮苎瑗氡跹芡蚜锨朊媸鋈嘞彘郧缣曛茀嬛潍伢颟佾谰搿笾豳轱戋舨蕖闼裰浞诎妗囝炔踬葚窳窣绂邗髌戢邶兕鹬蕡喾缗楂屙饧氰掊鎏辂烯狺墀戗崂晷遄蘧罴隳媵鸬捃傈渑酆椟睃鞯缇葳醚嘬酹诼嫠狍鳃裒悝黾毖唣澧圩鸶枘荇瀣狁螭幛踔棻蟊锒铗蛱鲑哞阍陔麂酡棰伕辚谳祧鍪莴邾迕颃獒郏邙龅涞疠舄褰莳璟禛垭铧呒铬觇赉蟮哓凇幂迮镒鲋蛴蝰饔轳咴谵鹈齑鄜厍褡跸荩洎麇絷僳芗酚骀蕞溆鳕爝峄粜瓿颙沣郯盱峁鸹琯艿茍墒薏舻缑谮驺鹚踅眬怿屄鹆犴儋逄嫱迓侂秫滹蔌噻澌洧缯扦裎邠镏琚秭錾棼髋戬枨葸漭荸馕铆堠濉葑璘蹓鳟氟圹榉伲锞珐豉鄞溱诜悫芩跽硎鹕肏蠓麀缡剀揎瘐呙绲酴屦芈蚴埽诖跶浥菔痖鲣瘗蛳镝埸雩虿笱鹓煅郾刭泚籼挢觌砷肽尕镍臁绁糁郫湜鹩蚨芃缵铱鲞窆敉菏萁湣筇瞀笫黧腚勐觱皤瘼笕嵊姮痤匄闶鲆阚蒉吣珲蟪窸邰蠛痧锛埤殂趵鄄熳癔锸珙箓蘩鏊鲔恧簏枞咮哏仳岵炝呔裣颡昉苁鼯荜翚鹁奡獯黟礌栘摅黡忮刖侉稞锼瘛汊嗉醅踣庥缫钲愔菹廑撙舣椐哕闫锶濞龆缳谂氚塍箨倮阌镪厣芑吡缧帻郗钋柽岀脞氦糍棨鄣逭忭钍眙羑慆觫邲眚硖搛獬岢徬轺蒗绱诹攮稊湔蜾煳釄钴饩莸鳜憯虼璠祎髁桕憷砀贶鲱僦鲥魈觔荽熘崾桬搧遹孓昺砻囟笪垡佺酤晬偾蹁骎柒叻贳艹糇枵腭锜忉舡胗泐浼艏斁跗劂涑鹨跩闿蒌蹀趱绠崃柙瘳歊嘒沬箬酯馓茭獍锑甙皲煸芪鹖萏苷鲷慉嫪嗌毐蚧朐湓陉蛏谫畈锳埏旰芨瞢芄鹇仡挼埘倊窨湑醛沭芏囷硷哚汔铂猃嗞窭涘嵝伃缬莜珦豨绨锬鞮趑跬劓螨皦氵锗嗐疃肷镠硐焓俜钛玠倓鄘驵苋狶芤傺骱薅钭粝鞒尥樘筲钕沩榇猰裥砟骟醁崦嫒痀螬绐甏浠蔾蛘鲟缂楦揸悰镆旐珧鳣啴肫玕猹菑摽坫糨絜钒疖瀼檩锔菪蛲肟芎嗍蚵瘆猞栌腩苤晡锓骍钚钨孢裢琎轵呯栝螓鬒裀怍鲅砹虮茑嘌玦艋骶赟馇嘧矬鲒骙畯鲦掹棬峣喤猁揠胂蠊鞲镈唪砊蚬崞垸龀胨鲙"
    },
    "font_manager": {
        "enable": true,
        "resource_files": [
            "SimHei.ttf"
        ],
        "spoof_creation": {
            "enable": true,
            "override_charset": 0,
            "override_face": "SimHei"
        }
    }
}
[injector] ======================================================
[injector] Injecting into module RealLive.exe at address 00400000
[injector] Loading original library from C:\Windows\system32\winmm.dll
[character_substitution] Loaded 3016 substitution characters
[character_substitution] Unable to hook import TextOutA because it does not exist
[character_substitution] Unable to hook import TextOutW because it does not exist
[character_substitution] Unable to hook import GetGlyphOutlineA because it does not exist
[character_substitution] Unable to hook import GetGlyphOutlineW because it does not exist
[font_manager] Imported 2 font(s) from SimHei.ttf
[font_manager] Unable to hook import CreateFontA because it does not exist
[font_manager] Unable to hook import CreateFontW because it does not exist
[font_manager] Unable to hook import CreateFontIndirectA because it does not exist
[font_manager] Unable to hook import CreateFontIndirectW because it does not exist
[font_manager] Unable to hook import CreateFontIndirectExA because it does not exist
[font_manager] Unable to hook import CreateFontIndirectExW because it does not exist
[injector] Initialization complete
[injector] ======================================================

</pre>
</details>

**Comment by AtomCrafty** [comment]
Looking at the segment table of that executable, it appears to be intentionally obfuscated to make reversing more difficult. UIF won't be able to work with this engine because of that.

**Comment by pxBang** [comment]
> Looking at the segment table of that executable, it appears to be intentionally obfuscated to make reversing more difficult. UIF won't be able to work with this engine because of that.

Well, thanks for your reply. I will look for other ways
