### ISSUE TITLE
QLIE engine

### ISSUE THREAD

**Issue by staciaa123** [AtomCrafty/UniversalInjectorFramework#9]
Game name: 美少女万華鏡異聞 雪おんな
The game will encounter an error if I switch to full-screen mode while using UIF hook.

![image](https://github.com/AtomCrafty/UniversalInjectorFramework/assets/155957757/0460349c-1fe1-4243-a20d-fcac0fea097c)

Game exe:
[game.exe.zip](https://github.com/AtomCrafty/UniversalInjectorFramework/files/15208231/game.exe.zip)

uif_config:
[uif_config.json](https://github.com/AtomCrafty/UniversalInjectorFramework/files/15208232/uif_config.json)

**Comment by AtomCrafty** [comment]
Looks like the `NCCREATE` handler is passed an invalid `lParam` for some reason. I've added a check to ignore the message in that scenario. Please pull the latest version and build your proxy again.

Fixed by 6aa9e1df9a00e779eda1abc97033a188cd17cde1
